### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Elfangor93** [creative-connections/Bodylight.js-FMU-Compiler#1]
I tried to install this Compiler. I have a windows 10 machine with docker installed. If I follow your installation istructions I get an error when I try to build the docker image
docker build -t bodylight.js.fmu.compiler "$(pwd)".

The command prompt (as administrator) tells me:
unable to prepare context: path "$(pwd)" not found

**Comment by david-polak** [comment]
Replace `"$(pwd)"` with the current directory. Either with a fully qualified path, or `.` might possibly work.

I will update the instructions to be platform agnostic once I get to a Windows workstation, possibly today.

**Comment by Elfangor93** [comment]
Replacing `"$(pwd)"` with `"."` worked ...

**Comment by david-polak** [comment]
The same issue will be with the 

```
docker run -d \
  --name bodylight.js.fmu.compiler \
  --mount type=bind,source="$(pwd)"/input,target=/input \
  --mount type=bind,source="$(pwd)"/output,target=/output \
  bodylight.js.fmu.compiler:latest bash worker.sh
```
command

try 

```
docker run -d --name bodylight.js.fmu.compiler --mount type=bind,source=./input,target=/input  --mount type=bind,source=./output,target=/output  bodylight.js.fmu.compiler:latest bash worker.sh
```

**Comment by Elfangor93** [comment]
Thats what I get:
![grafik](https://user-images.githubusercontent.com/39154009/54420677-f0666c00-470a-11e9-8124-a6c2321d633a.png)

**Comment by Elfangor93** [comment]
This one doesnt create any error:
![grafik](https://user-images.githubusercontent.com/39154009/54421157-1fc9a880-470c-11e9-9835-355e68e22ecc.png)

The container is up and running, but it doesent seem to do anything...
Do I have to start the compilation somehow?

**Comment by david-polak** [comment]
Usage
Put name.fmu files into the input directory. After the compilation finishes, input/name.fmu is deleted and the resulting name.js file is copied to output. Along with the compilation log name.log.

Files are processed sequentially in alphabetical order.

In case of error, only the compilation log will be present in the output directory.

**Comment by Elfangor93** [comment]
Some hours past, I placed a fmu-file in the input folder, but till now nothing happend not in the input nor in the output folder...
If I try to start the compiler again it tells me, that it is already in use:
![grafik](https://user-images.githubusercontent.com/39154009/54431935-033b6980-4728-11e9-8a35-5f0f2842e9c5.png)
Seems as if something is not working correctly on windows.

**Comment by david-polak** [comment]
@19leunam93 Please try the new instructions in the README, there is an infamous problem with INotify not working under Windows, which nobody fixed yet.

**Comment by Elfangor93** [comment]
Now it worked, if I run the comand prompt as administrator and if I exchange `$(Get-Location)` with a manuel entered path.

**Comment by david-polak** [comment]
I tested it with PowerShell, I don't recall if I needed administrator privileges for that, but the commands should work in PowerShell without any alterations.

**Comment by Elfangor93** [comment]
I will try it with powerShell. With CommandPrompt `$(Get-Location)` doesn't work...
