### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by BhushanWagh22** [creative-connections/Bodylight.js-FMU-Compiler#10]
1. I tried installing with virtual machine but its throwing an error when I run "vagrant up" 
![Screenshot (330)](https://user-images.githubusercontent.com/109505579/236456554-1bfc989e-0d90-451e-b96f-8c466ed963a8.png)
2. I tried with docker too but again it is also not working
![Screenshot (332)](https://user-images.githubusercontent.com/109505579/236456740-e2d2b953-f3ae-4281-91bc-b64a5a471ce1.png)

**Comment by TomasKulhanek** [comment]
With preinstalled vm you need to download it from https://filedn.com/lHGc7w3H4jOpIe46u1nPt57/BodyligthVMImage/22.09/bodylightvm.box or change Vagrantfile to download it from that location. Commited update to link to the newest VM iamge.
