### ISSUE TITLE
compilation of FMU from OpenModelica fails

### ISSUE THREAD

**Issue by Elfangor93** [creative-connections/Bodylight.js-FMU-Compiler#3]
The compilation of the following FMU (exported from OpenModelica) fails on Windows.
I already discoverd, that Emscripten only compiles correct, if you start the compilation with `emcc -I include/ MyModel.c` . I dont know how you start the compilation with emscripten - maybe thats the problem...

FMU-File:
https://drive.switch.ch/index.php/s/a4FHJIqYtSozC4j

Log-File:
[TankSystem_Wassertank_OM.log](https://github.com/creative-connections/Bodylight.js-FMU-Compiler/files/2992340/TankSystem_Wassertank_OM.log)

**Comment by david-polak** [comment]
I see you are using OpenModelica for the compilation of the FMU (which I can't access) 

Are you using [creative-connections/Bodylight.js-OM-Compiler](https://github.com/creative-connections/Bodylight.js-OM-Compiler) to export the FMU?

**Comment by Elfangor93** [comment]
No, I used a standard OpenModelica installation on Windows...

**Comment by david-polak** [comment]
Yeah, unfortunately that won't work, firstly because of [this PR](https://github.com/OpenModelica/OMCompiler/pull/2806) which is needed for Composer and which hasn't gotten to the release version of OM yet.

And secondly, OM creates platform *and* system dependent makefiles with no easy way to regenerate them. 

For example, from your logfile
```"C:/Users/tbhaeusl/Documents/Dateien/SwitchCloud/000718_DigitalerPruefstand_InnoLehre7/Thomas/TankSystem"    -falign-functions -msse2 -mfpmath=sse  -L"C:/OpenModelica1.12.0-64bit//lib//omc" -Wl,-rpath,"C:/OpenModelica1.12.0-64bit//lib//omc" -lregex -lexpat -lomcgc -lpthread -fopenmp``` 
paths for compilation are actually baked in in the outputed FMU.

It is easier to just use the [OM Compiler](https://github.com/creative-connections/Bodylight.js-OM-Compiler) approach than to try and fix OpenModelica with the regard to the FMU source code generation.

**Comment by Elfangor93** [comment]
Oke, I tried now the way with OM Compiler. The following Model needs to be transformed to JavaScript:
![grafik](https://user-images.githubusercontent.com/39154009/55542933-515ce080-56c8-11e9-8579-d0d4e8338c5b.png)


Two errors accoured with this model:

1. The FMU created by OM Compiler cant be opend. The Error in FMPy: 
> Failed to load .../BouncingBall.fmu. The unit 'm/s2' of variable 'a' is not defined.

-> after removing of the unit that worked

2. It looked as if the fmu now should work. But after running the FMU Compiler on that BouncingBall.fmu I got the following error:
> ERROR:root:build/fmu/sources/all.c: No such file or directory ("build/fmu/sources/all.c" was expected to be an input file, based on the commandline arguments provided)

-> No js-File was created...

In the attachment I sent you all the files (mo, fmu, zip, log) of the version without unit 'm/s2'
[BouncingBall.zip](https://github.com/creative-connections/Bodylight.js-FMU-Compiler/files/3042575/BouncingBall.zip)

**Comment by Elfangor93** [comment]
So it looks, as if OM Compiler has troubles with units in its models...

**Comment by Elfangor93** [comment]
And that FMU Compiler cant find all ressources in the fmu-file exported with the OM Compiler (at least on a windows machine)

**Comment by david-polak** [comment]
Fixed the compilation issue, it looked for `all.c` and found `BouncingBall.c`, slightly embarrassing.

**Comment by Elfangor93** [comment]
it worked now with the new version...
