### ISSUE TITLE
Request for simple example .fmu file to test with

### ISSUE THREAD

**Issue by AJamesPhillips** [creative-connections/Bodylight.js-FMU-Compiler#7]
I have a simple model:

    model LorenzAttractor
      parameter Real sigma = 10;
      parameter Real rho = 28;
      parameter Real beta = 8/3;
      Real x (start=1);
      Real y (start = 1);
      Real z (start = 1);
    equation
      der(x) = sigma*(y-x);
      der(y) = x * (rho-z) - y;
      der(z) = x*y - beta*z;
    end LorenzAttractor;

I exported this to [a .fmu file](https://github.com/creative-connections/Bodylight.js-FMU-Compiler/files/7715055/LorenzAttractor.fmu.zip) to the `/input` directory whilst the Bodylight.js-FMU_Compiler docker process was running.  It does not seem to be converted nor an error log put into `/output`.  Would it be possible to add a simple example `.fmu` that I could test my set up with please?  I also tried accessing the docker container via the command line but I haven't yet found a way to monitor / tail the logging from the system as I add a new .fmu file to the `/input` directory.

Thank you very much for your time and consideration.  I'm looking forward to using the tool.

**Comment by AJamesPhillips** [comment]
Perhaps this is related to #4 ?  I don't have an option to specify the Solver as Explicit Euler in the OMEdit I'm using (Mac, 1.18.0~dev-109-ged8ef0a)?

**Comment by shjiang** [comment]
> I have a simple model:
> 
> ```
> model LorenzAttractor
>   parameter Real sigma = 10;
>   parameter Real rho = 28;
>   parameter Real beta = 8/3;
>   Real x (start=1);
>   Real y (start = 1);
>   Real z (start = 1);
> equation
>   der(x) = sigma*(y-x);
>   der(y) = x * (rho-z) - y;
>   der(z) = x*y - beta*z;
> end LorenzAttractor;
> ```
> 
> I exported this to [a .fmu file](https://github.com/creative-connections/Bodylight.js-FMU-Compiler/files/7715055/LorenzAttractor.fmu.zip) to the `/input` directory whilst the Bodylight.js-FMU_Compiler docker process was running. It does not seem to be converted nor an error log put into `/output`. Would it be possible to add a simple example `.fmu` that I could test my set up with please? I also tried accessing the docker container via the command line but I haven't yet found a way to monitor / tail the logging from the system as I add a new .fmu file to the `/input` directory.
> 
> Thank you very much for your time and consideration. I'm looking forward to using the tool.

I have tried this tool.  The attached files are the .mo file the .fmu file that have tested with no problem.  The model is very simple:

model MyTest
  Real y;
  parameter Integer lambda = 1;
equation 
  y = sin(time*lambda);
  annotation (experiment(StopTime=100, __Dymola_Algorithm="Dassl"));
end MyTest;

[MO&FMU.zip](https://github.com/creative-connections/Bodylight.js-FMU-Compiler/files/7718790/MO.FMU.zip)

Also attached the exported html project:
[MyTestHtml.zip](https://github.com/creative-connections/Bodylight.js-FMU-Compiler/files/7718818/MyTestHtml.zip)

Hopes it will help although I am still a newbie to it.

**Comment by AJamesPhillips** [comment]
Interesting.  Thank you very much @shjiang !  I will close this issue and open a new one.
