### ISSUE TITLE
Request for help to find logs to debug problems

### ISSUE THREAD

**Issue by AJamesPhillips** [creative-connections/Bodylight.js-FMU-Compiler#8]
With the docker container running (as per the instructions in the README), when I put an `.fmu` file into the input directory nothing seems to happen.  I have tried both the fmu files from #7.  I have tried starting and stopping the container.  I have tried looking inside the container for any logging files or error messages but have not yet successfully found anything to help debug the problem.

If you had any advice on how to debug the issue I would be grateful to receive it and I would be happy to add a PR to add this to the README.

**Comment by AJamesPhillips** [comment]
I've just seen the logs in the docker container that says:

>  Setting up watches.  Beware: since -r was given, this may take a while!
> 
> Watches established.

It still seems unresponsive when I drag a .fmu file into the `./Bodylight.js-FMU-Compiler/input` directory whilst the docker image is running.

**Comment by TomasKulhanek** [comment]
Thank you for reporting. The docker configuration uses older emscripten. Currently we do not have anybody to maintain it. Thus I recommend to use VM configuration.
