### ISSUE TITLE
Something wrong with the compiler in VM box

### ISSUE THREAD

**Issue by shjiang** [creative-connections/Bodylight.js-FMU-Compiler#9]
I have tested a simple project both with docker and VM box. The .mo and .FMU files are here,
[MyTest_mo&FMU.zip](https://github.com/creative-connections/Bodylight.js-FMU-Compiler/files/7731302/MyTest_mo.FMU.zip)
There were no errors during the compiling process,  as shown in the log file. However, it is found that the generated files are different. The VM generated modelDescription.xml and name.js, while the docker generated name.xml and name.js. In addition, the size of js files is different. When looking into the log file, the VM generated fewer warnings than the docker did during compiling (52 vs 116). 
I have attached the generated files here. Really hope someone can help. Thanks a lot! 
[MyTest_from VM.zip](https://github.com/creative-connections/Bodylight.js-FMU-Compiler/files/7731339/MyTest_from.VM.zip)
[mytest_from docker.zip](https://github.com/creative-connections/Bodylight.js-FMU-Compiler/files/7731340/mytest_from.docker.zip)

**Comment by TomasKulhanek** [comment]
Thank you for testing this repo. Docker version uses older EMScripten to compile. VM version uses newer one. This is the reason why logs differs. The logs contains warnings regarding generated C-source codes from Dymola. The warning can be ignored.
